name: $(Year:yy).$(Month).$(DayOfMonth).$(rev:r)

pr:
  branches:
    include:
      - main
      - feature/*
      - release/*

trigger:
  branches:
    include:
      - main
      - feature/*
      - release/*
  batch: true

variables:
  solution: source/dotnet/AdaptiveCards.sln
  buildConfiguration: Release
  buildPlatform: any cpu

pool:
  name: Azure Pipelines
  vmImage: windows-2019

steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK'
    inputs:
      version: 5.x

  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet'
    inputs:
      versionSpec: 5.x

  - task: NuGetCommand@2
    displayName: 'NuGet restore'
    inputs:
      command: 'restore'
      restoreSolution: '$(solution)'
      feedsToUse: 'config'

  - task: VSBuild@1
    displayName: 'Build solution $(solution)'
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: VSTest@2
    displayName: 'Run unit tests'
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        **\!(ref)\*.test.dll
        !**\obj\**
      searchFolder: '$(System.DefaultWorkingDirectory)\source\dotnet'
      runSettingsFile: ''
      codeCoverageEnabled: true
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      diagnosticsEnabled: true

  - task: PowerShell@2
    displayName: 'Run additional tests'
    inputs:
      targetType: 'inline'
      script: |
        # Add any additional test commands here

  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    displayName: 'Component Detection'
